version: '3.7'
services:
  surveyio_service:
    image: nginxdemos/hello:plaintext
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0
        order: start-first
    ports:
    - 8686:80
