name: BurpSuite

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    runs-on: ubuntu-latest
    container: tareksrour/burp
    env:
      URL: "https://ginandjuice.shop"
    steps:
    - uses: actions/checkout@v2  
    - run: /app/entrypoint.sh
      shell: bash
    - run: tojunit
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Burp Test Result            # Name of the check run which will be created
        path: './junit-report.xml'
        reporter: java-junit
        fail-on-error: false
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: scan-report
        path: |
          burp-report.xml
          burp-report.html
          junit-report.xml