name: Burp2

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    runs-on: ubuntu-latest
    container: tareksrour/burp
    env:
      URL: "https://ginandjuice.shop"
    steps:
    - run: |
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
        <config xmlns=\"http://nets.eu/burp/config\">
          <reportType>HTML</reportType>
          <targetSitemap><![CDATA[$URL]]></targetSitemap>
          <scope>
            <url><![CDATA[$URL]]></url>
          </scope>
        </config>" > config.xml
      shell: bash
    - run: java -Xbootclasspath/p:ESEdition.jar -Xmx1G -Djava.awt.headless=true -noverify -classpath headless-burp-scanner-master-SNAPSHOT-jar-with-dependencies.jar:burpsuite_pro_v1.7.34.jar burp.StartBurp --unpause-spider-and-scanner --project-file=project.burp -c config.xml
      shell: bash
    # You can replace this next step with any JUnit XML parser of your choosing
    # - name: Publish Test Report
    #   if: always()                                    # Forces this step to always run
    #   uses: mikepenz/action-junit-report@v3
    #   with:
    #     report_paths: '**/dastardly-report.xml'       # You need to update this path if you pass in a different output filename to the Dastardly action
    #     require_tests: true
    #     detailed_summary: true