name: BurpSuite Scan

on:
  workflow_dispatch:
    inputs:
      url:
        required: false
        type: string
      scope:
        required: false
        type: string
      runs_on:
        required: false
        default: "ubuntu-latest"
      severity_level:
        required: false
        type: choice
        default: Information
        options:
          - Information
          - Low
          - Medium
          - High

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    runs-on: ${{ inputs.runs_on}}
    services:
      burp-api:
        image: tareksrour/burp-api
        ports:
          - 8080:8080
          - 8090:8090
      tojunit:
        image: tareksrour/tojunit:server
        ports:
          - 8888:8888
    container: 
      image: alpine:3.14
      # credentials:
      #   username: ${{ secrets.HARBOR_REGISTRY_USER_QA }}
      #   password: ${{ secrets.HARBOR_REGISTRY_PASSWORD_QA }}
    env:
      URL: ${{ inputs.url }}
      SCOPE: ${{ inputs.scope }}
      HTTP_PROXY: http://burp-api:8080
      HTTPS_PROXY: http://burp-api:8080
      # http_proxy: http://localhost:8080
      # https_proxy: http://localhost:8080
      # no_proxy: localhost,127.0.0.1
      NO_PROXY: localhost,127.0.0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install curl
      run: HTTP_PROXY= HTTPS_PROXY= apk add curl git
    - name: Wait for proxy to become available
      run: |
        sleep 10
        while ! nc -z localhost 8080; do   
          sleep 1
        done
    - name: Do selenium test over proxy
      run: curl $URL -k -x $HTTP_PROXY
    - name: Set Target Scope
      run: |
        curl "http://burp-api:8090/burp/target/scope?url=${{ env.URL }}" -X PUT -s
    - name: Spider Routes
      run: |
        echo Sending Sitemap to Spider
        for url in $(curl "burp-api:8090/burp/proxy/history" -s| jq ' .messages[] | select(.host=="$(echo ${{ env.URL }} | cut -d / -f3)")' | jq .url -r | xargs)
        do
          curl "burp-api:8090/burp/spider" -X POST --data-urlencode "baseUrl=$url" -s
        done
        echo Waiting Spider to finish
        echo 0% Spider Done
        sleep 5
        while : ; do
        sprider_progress=$(curl "burp-api:8090/burp/spider/status" -s | jq .spiderPercentage -r)
        [[ $sprider_progress -eq 100 ]] && break
          echo -e "\e[1A\e[K$sprider_progress% Spider done"
        done
    - name: Active Scan
      run: |
        echo Starting Active Scan
        curl burp-api:8090/burp/scanner/scans/active --data-urlencode "baseUrl=${{ env.URL }}" -X POST -s
        echo 0% Scan done
        while : ; do
          scan_progress=$(curl http://burp-api:8090/burp/scanner/status -s | jq .scanPercentage -r)
          [[ $scan_progress -eq 100 ]] && break
          echo -e "\e[1A\e[K$scan_progress% Scan done"
          sleep 10
        done
    - name:  Generating Reports
      run: |
        curl "http://burp-api:8090/burp/report?reportType=HTML&issueSeverity=All&issueConfidence=All&urlPrefix=${{ env.URL }}" -o burp-report.html -s
        curl "http://burp-api:8090/burp/report?reportType=XML&issueSeverity=All&issueConfidence=All&urlPrefix=${{ env.URL }}" -o burp-report.xml -s
        curl http://tojunit:8888/?severity=${{ inputs.severity_level }} -X POST -d @burp-report.xml > junit-report.xml
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Burp Test Result            # Name of the check run which will be created
        path: './junit-report.xml'
        reporter: java-junit
        fail-on-error: false
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: scan-report
        path: |
          burp-report.xml
          burp-report.html
          junit-report.xml
    - name: Cleanup
      if: always()
      run: rm -rf *