name: debug

on:
  push:
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           repository: t-demo-org/triggered-repo
