name: Dastardly

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Run Dastardly Action Step
      continue-on-error: true                        # This allows subsequent steps to run even if this step fails
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: 'https://ginandjuice.shop'
    - run: find / | grep dastardly-report.xml  && pwd
    # - name: Test Report
    #   uses: dorny/test-reporter@v1
    #   if: success() || failure()    # run this step even if previous step failed
    #   with:
    #     name: Dastardly Test Result            # Name of the check run which will be created
    #     path: '**/dastardly-report.xml'    # Path to test results
    #     reporter: java-junit    
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: dastardly-report
        path: './dastardly-report.xml'
    # You can replace this next step with any JUnit XML parser of your choosing
