name: Burp

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Run Dastardly Action Step
      continue-on-error: true                        # This allows subsequent steps to run even if this step fails
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: 'https://ginandjuice.shop'
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Dastardly Test Result            # Name of the check run which will be created
        path: '**/dastardly-report.xml'    # Path to test results
        reporter: jest-junit    
    # You can replace this next step with any JUnit XML parser of your choosing
