# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  high_env: high

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 one-time:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.event.commits[0].author.email }}"
#     - name: Trigger Deploy
#       uses: convictional/trigger-workflow-and-wait@v1.6.1
#       with:
#         owner: t-demo-org
#         repo: triggered-repo
#         github_token: ${{ secrets.GIT_TOKEN }}
#         ref: master
#         workflow_file_name: triggered.yml

# #     container: docker:20.10
# #     services:
# #       docker: 
# #         env:
# #           DOCKER_TLS_CERTDIR: ""
# #         image: docker:20.10-dind
# #         ports:
# #         - 2375:2375
# #         options: >-
# #           --privileged
# #           --health-cmd "docker ps"
# #           --health-interval 10s
# #           --health-timeout 5s
# #           --health-retries 5
# #     steps:
# #     - name: Checkout Devops
# #       uses: actions/checkout@v2
# #       env:
# #         DOCKER_HOST: tcp://docker:2375
# #         DOCKER_TLS_CERTDIR: ""
# #     - name: test
# #       run: |
# #         ls -lah
# #         if ! nc -z docker 2375; then
# #           echo reachable
# #         fi
# #         export DOCKER_HOST=tcp://docker:2375
# #         export DOCKER_TLS_CERTDIR=""
# #         docker pull alpine
# #         docker images

