# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  high_env: high

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 one-time:
    runs-on: ubuntu-latest
    container: maven:3.6-8
    steps:
      - run: apt update && apt install git zip -y
      - run: which git && which zip
