# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  high_env: high

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 one-time:
    runs-on: ubuntu-latest
    container: alpine:3.14
    steps:
      - run: cat /etc/*release*
 tester:
    # The type of runner that the job will run on
    uses: t-demo-org/triggered-repo/.github/workflows/tester.yml@master  
 generator:
    # The type of runner that the job will run on
    needs: [tester]
    uses: t-demo-org/triggered-repo/.github/workflows/generator.yml@master  

