# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  high_env: high

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 one-time:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
    container: docker:20.10-dind
    services:
      docker: 
        env:
          DOCKER_TLS_CERTDIR: ""
        image: docker:20.10-dind
        ports:
        - 2375:2375
        options: >-
          --privileged
          --health-cmd "docker ps"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - run: |
        docker pull alpine
        docker images

